[package]
name = "tfs"
version = "0.1.0"
authors = ["ticki <ticki@users.noreply.github.com>"]

[dependencies]
byteorder = "0"
quick-error = "1"
lz4-compress = "0"
speck = "0"
seahash = "3"

[features]
security = []
